Fail compilation early and with a proper message on unsupported architectures.
Attempting to compile the project on non-x86 architecture fails with the error
message below. Which is quite difficult to understand without examining the
[source code](https://github.com/AccelerateHS/accelerate-llvm/blob/master/accelerate-llvm-native/icebox/Data/Array/Accelerate/LLVM/Native/Link/ELF.chs#L442).

```
[ 6 of 35] Compiling Data.Array.Accelerate.LLVM.Native.Link.ELF ( .stack-work/dist/arm-linux/Cabal-2.4.0.1/build/Data/Array/Accelerate/LLVM/Native/Link/ELF.hs, .stack-work/dist/arm-linux/Cabal-2.4.0.1/build/Data/Array/Accelerate/LLVM/Native/Link/ELF.o )

/tmp/stack-1d292616/accelerate-llvm-native-1.3.0.0/src/Data/Array/Accelerate/LLVM/Native/Link/ELF.chs:216:1: error:
    The type signature for ‘processRelocation’
      lacks an accompanying binding
    |
216 |           dst = seg_p `plusPtr` sec_addr
    | ^^^^^^^^^^^^^^^^^

/tmp/stack-1d292616/accelerate-llvm-native-1.3.0.0/src/Data/Array/Accelerate/LLVM/Native/Link/ELF.chs:431:25: error:
    Not in scope: type constructor or class ‘RelocationType’
    Perhaps you meant one of these:
      ‘Relocation’ (line 426), ‘SectionType’ (line 290)
    |
431 |     , r_type        :: !RelocationType
    |                         ^^^^^^^^^^^^^^
```